# Generated by Django 3.2.5 on 2021-07-22 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_category_comment_listing_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='date',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='active',
        ),
        migrations.AddField(
            model_name='listing',
            name='image_link',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='buyer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
