# Generated by Django 3.2.5 on 2021-07-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210722_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='startbid',
            field=models.IntegerField(),
        ),
    ]
